version: '3.8'
services:
  idp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/idp
      - PRIVATE_KEY_PATH=/app/keys/private.pem
      - PUBLIC_KEY_PATH=/app/keys/public.pem
    volumes:
      - ./app:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=idp
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: